# Generated by Django 3.1.4 on 2020-12-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nija', to='nija.dojo')),
            ],
        ),
    ]
